title = "Freifunk Köln, Bonn & Umgebung"
baseURL = "https://kbu.freifunk.net/"
#baseURL = ""
languageCode = "de-de"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "de"
#SectionPagesMenu = "main"
Paginate = 40 # this is set low for demonstrating with dummy content. Set to a higher number
#googleAnalytics = ""
enableRobotsTXT = true

#[sitemap]
#  changefreq = "monthly"
#  priority = 0.5
#  filename = "sitemap.xml"

[params]
  favicon = "https://kbu.freifunk.net/images/icons/logo.ico"
  site_logo = "https://kbu.freifunk.net/images/logo.png"
  description = ""
  facebook = ""
  twitter = "https://twitter.com/freifunkkbu"
  instagram = ""
  youtube = ""
  github = "https://github.com/ff-kbu"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
#  featured_image = "/images/headerbonn2.jpg"
  custom_css = ["/css/custom.css", "/css/fontawsome/css/all.min.css"]
  cover_dimming_class = "bg-black-40"
  recent_posts_number = 40


[[menu.main]]
pre = "<i class='fas fa-question'></i>"
name = "Was ist Freifunk"
url ="/wasistfreifunk/"
weight=1

[[menu.main]]
pre = "<i class='fas fa-user-friends'></i>"
name = "Mitmachen"
url ="/mitmachen/"
weight= 2

[[menu.main]]
pre = "<i class='fas fa-comment'></i>"
name = "Kontakt"
url = "/kontakt/"
weight= 3

[[menu.main]]
pre = "<i class='fas fa-map'></i>"
name = "Karte"
url = "http://map.kbu.freifunk.net/"
weight= 4

[[menu.main]]
pre = "<i class='fas fa-info'></i>"
name = "Wiki"
url = "https://kbu.freifunk.net/wiki/"
weight= 5

[[menu.main]]
pre = "<i class='fas fa-user-shield'></i>"
name = "Datenschutz"
url = "/datenschutz/"
weight= 6

